// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFaycVZzp8SajOqwZSaxRYSfODziJ-1cM',
    appId: '1:733776137006:web:36b8d836bc9d1893cb48bf',
    messagingSenderId: '733776137006',
    projectId: 'notify-me-d1680',
    authDomain: 'notify-me-d1680.firebaseapp.com',
    storageBucket: 'notify-me-d1680.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNezLDEJ-fYBo51J_ie2V33GcjCrYEBXE',
    appId: '1:733776137006:android:f35149d2fd436e89cb48bf',
    messagingSenderId: '733776137006',
    projectId: 'notify-me-d1680',
    storageBucket: 'notify-me-d1680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuBb-m7ais-fH8-nqS1X_XhfoRi-qElho',
    appId: '1:733776137006:ios:d6d20c31589fcba0cb48bf',
    messagingSenderId: '733776137006',
    projectId: 'notify-me-d1680',
    storageBucket: 'notify-me-d1680.appspot.com',
    androidClientId: '733776137006-t2hh2k3uk5odvdl4jmpssioh4l4qihhl.apps.googleusercontent.com',
    iosClientId: '733776137006-7v20815fk88kh0hn6ck7gkqgq0ls1f93.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifyMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuBb-m7ais-fH8-nqS1X_XhfoRi-qElho',
    appId: '1:733776137006:ios:d6d20c31589fcba0cb48bf',
    messagingSenderId: '733776137006',
    projectId: 'notify-me-d1680',
    storageBucket: 'notify-me-d1680.appspot.com',
    androidClientId: '733776137006-t2hh2k3uk5odvdl4jmpssioh4l4qihhl.apps.googleusercontent.com',
    iosClientId: '733776137006-7v20815fk88kh0hn6ck7gkqgq0ls1f93.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifyMe',
  );
}
